"""Runtime Ports ABI——Fragment / API / Product 面向的端口面。

包路径保持 ``app.core.runtime.read_ports`` 不变以维持稳定；其角色比投影
读取更广。调用方经这些端口而不是直接开 DB 会话、导入 ORM 模型或触达深层
Runtime 模块（``work_item_engine``、``reaction_registry``、桥、调度器内部）。

    调用方 → Port → Kernel / Runtime 内部

按域拆分在本包下。包括：

- **读** —— 受治理投影查询（``query_*`` / ``count_*``）
- **命令** —— Work 变更、触发器注册（惰性包装）
- **桥** —— SSE 队列注册/注销、通知推送

经 ``from app.core.runtime.read_ports import …`` 或
``from app.core.runtime import read_ports`` 导入。
"""

from app.core.runtime.notification_bridge import NotificationPayload
from app.core.runtime.read_ports.approvals import (
    query_approval,
    query_approvals,
    query_pending_approval_count,
    query_pending_approvals,
)
from app.core.runtime.read_ports.calendar_mcp import (
    get_mcp_server_status,
    get_mcp_server_tools,
    query_calendar_today_events,
    query_calendar_upcoming,
    query_world_context,
    test_mcp_connection,
)
from app.core.runtime.read_ports.conversation import (
    get_conversation_sources,
    query_conversation,
    query_conversation_messages,
    query_conversations,
    query_message,
)
from app.core.runtime.read_ports.events import (
    goal_events,
    query_recent_events,
    recent_events,
    reconstruct_execution_trace,
    to_event_dict,
)
from app.core.runtime.read_ports.inbox import (
    count_pending_inbox_emails,
    query_inbox_email,
    query_inbox_emails,
    query_latest_inbox_poll,
    query_pending_inbox_emails,
    query_recent_inbox_emails,
    search_inbox_emails,
    summarize_inbox_sync_metrics,
)
from app.core.runtime.read_ports.memory import (
    build_memory_graph_edges,
    count_memories,
    query_memories,
    query_memory,
    recall_memories_for_context,
    retrieve_memory_context,
    retrieve_memory_with_sources,
    summarize_memory_stats,
)
from app.core.runtime.read_ports.notifications import (
    create_notification,
    find_notification,
    push_notification,
    query_notification,
    query_notifications,
    query_unread_notification_count,
    register_sse_queue,
    unregister_sse_queue,
)
from app.core.runtime.read_ports.profile import (
    query_user_profile,
    query_user_profile_category,
)
from app.core.runtime.read_ports.telemetry import (
    query_llm_calls,
    query_recent_tool_names,
    query_tool_calls,
    summarize_call_failure_rates,
    summarize_llm_calls,
    summarize_llm_calls_by_model,
    summarize_tool_calls,
)
from app.core.runtime.read_ports.timers import (
    count_active_policies,
    count_active_timers,
    count_state_selectors,
    list_trigger_reactions,
    query_active_policies,
    query_active_timers,
    query_due_timers,
    query_timer,
    register_trigger_reaction,
    unregister_trigger_reaction,
)
from app.core.runtime.read_ports.work import (
    bump_parent_activity,
    cancel_background_work_item,
    count_active_goals,
    count_completed_goals,
    count_goals,
    create_work_item,
    delete_work_item,
    get_sub_work_items,
    get_work_item_tree,
    list_work_items,
    notify_goal_action_completed,
    query_active_goals,
    query_background_work_item,
    query_background_work_items,
    query_completed_goals,
    query_goal,
    query_goal_actions,
    query_goals,
    query_goals_with_deadline,
    query_pending_work_items,
    query_stagnant_goal_count,
    query_stagnant_goals,
    query_top_active_goals,
    query_work_item,
    query_work_items,
    query_work_items_by_parent_goal,
    request_work_item_execute,
    update_work_item_fields,
    update_work_item_status,
    work_item_execution_snapshot,
)

__all__ = [
    "count_active_goals",
    "count_completed_goals",
    "count_goals",
    "count_memories",
    "summarize_memory_stats",
    "query_pending_work_items",
    "query_top_active_goals",
    "query_stagnant_goals",
    "query_stagnant_goal_count",
    "query_work_item",
    "query_work_items",
    "query_goals",
    "query_goal",
    "query_goal_actions",
    "query_work_items_by_parent_goal",
    "query_active_goals",
    "query_completed_goals",
    "query_goals_with_deadline",
    "create_work_item",
    "request_work_item_execute",
    "work_item_execution_snapshot",
    "update_work_item_fields",
    "update_work_item_status",
    "delete_work_item",
    "get_sub_work_items",
    "get_work_item_tree",
    "list_work_items",
    "bump_parent_activity",
    "recall_memories_for_context",
    "retrieve_memory_context",
    "retrieve_memory_with_sources",
    "query_memory",
    "query_memories",
    "notify_goal_action_completed",
    "query_conversation_messages",
    "query_conversation",
    "query_conversations",
    "query_message",
    "get_conversation_sources",
    "query_recent_inbox_emails",
    "search_inbox_emails",
    "query_pending_inbox_emails",
    "count_pending_inbox_emails",
    "query_inbox_email",
    "query_inbox_emails",
    "query_latest_inbox_poll",
    "summarize_inbox_sync_metrics",
    "query_pending_approval_count",
    "query_pending_approvals",
    "query_approval",
    "query_approvals",
    "query_notification",
    "query_notifications",
    "query_unread_notification_count",
    "NotificationPayload",
    "create_notification",
    "find_notification",
    "push_notification",
    "register_sse_queue",
    "unregister_sse_queue",
    "query_llm_calls",
    "query_tool_calls",
    "query_recent_tool_names",
    "summarize_llm_calls",
    "summarize_llm_calls_by_model",
    "summarize_tool_calls",
    "summarize_call_failure_rates",
    "query_world_context",
    "query_calendar_upcoming",
    "query_calendar_today_events",
    "get_mcp_server_status",
    "get_mcp_server_tools",
    "test_mcp_connection",
    "query_background_work_item",
    "query_background_work_items",
    "cancel_background_work_item",
    "query_active_timers",
    "count_active_timers",
    "query_timer",
    "query_due_timers",
    "query_active_policies",
    "count_active_policies",
    "register_trigger_reaction",
    "list_trigger_reactions",
    "unregister_trigger_reaction",
    "count_state_selectors",
    "query_user_profile_category",
    "query_user_profile",
    "to_event_dict",
    "goal_events",
    "recent_events",
    "query_recent_events",
    "reconstruct_execution_trace",
    "build_memory_graph_edges",
]
